/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package builders.marketplace.api

import io.ktor.server.netty.*

fun main(args: Array<String>): Unit = EngineMain.main(args)


