/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package builders.marketplace

import builders.marketplace.routes.registerCustomerRoutes
import io.ktor.application.Application
import io.ktor.application.install
import io.ktor.features.ContentNegotiation
import io.ktor.gson.gson
import io.ktor.server.netty.EngineMain

fun main(args: Array<String>): Unit = EngineMain.main(args)

fun Application.module() {
    install(ContentNegotiation) {
        gson()
    }
    registerCustomerRoutes()
}
