/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package builders.marketplace

import io.ktor.application.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import java.util.concurrent.TimeUnit.SECONDS

object App {
    private val server = embeddedServer(factory = Netty, port = 8080) {
        routing {
            get("/") {
                call.respondText(text = "Hello Kotlin", contentType = ContentType.Text.Html)
            }
        }
    }

    fun run() {
        server.start(wait = true)
    }

    fun stop() {
        server.stop(gracePeriod = 1, timeout = 1, timeUnit = SECONDS)
    }
}

fun main(args: Array<String>) {
    App.run()
}
