/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package builders.marketplace

import io.kotest.assertions.ktor.*
import io.kotest.core.spec.style.AnnotationSpec
import io.kotest.core.test.TestCase
import io.kotest.core.test.TestResult

class AppTest: AnnotationSpec() {

    override fun beforeTest(testCase: TestCase) {
        App.run()
    }

    @Test
    fun testAppHasAGreeting() {
        val client = HttpClient(CIO)
    }

    override fun afterTest(testCase: TestCase, result: TestResult) {
        App.stop()
    }
}
