/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package builders.marketplace

import io.kotest.core.spec.style.AnnotationSpec
import io.kotest.matchers.shouldBe
import io.ktor.http.HttpMethod
import io.ktor.server.testing.handleRequest
import io.ktor.server.testing.withTestApplication

class AppTest : AnnotationSpec() {

    @Test
    fun testAppHasAGreeting() {
        withTestApplication({ module() }) {
            val response = handleRequest(HttpMethod.Get, "/").response.content
            response shouldBe null
        }
    }
}
